[versions]
agp = "8.5.0"
kotlin = "1.9.24"
compose = "1.6.8"
composeCompiler = "1.5.14"
hilt = "2.51.1"
lifecycle = "2.8.4"
firebaseBom = "33.1.1"
coroutines = "1.8.1"

[libraries]
androidx-core = "androidx.core:core-ktx:1.13.1"
androidx-lifecycle-runtime = "androidx.lifecycle:lifecycle-runtime-ktx:{lifecycle}"
androidx-lifecycle-viewmodel = "androidx.lifecycle:lifecycle-viewmodel-ktx:{lifecycle}"
androidx-activity-compose = "androidx.activity:activity-compose:1.9.0"
androidx-compose-ui = "androidx.compose.ui:ui:{compose}"
androidx-compose-material = "androidx.compose.material3:material3:1.2.1"
androidx-compose-foundation = "androidx.compose.foundation:foundation:{compose}"
androidx-compose-tooling = "androidx.compose.ui:ui-tooling-preview:{compose}"
androidx-navigation-compose = "androidx.navigation:navigation-compose:2.7.7"
androidx-paging-compose = "androidx.paging:paging-compose:3.3.0"
androidx-hilt-navigation-compose = "androidx.hilt:hilt-navigation-compose:1.2.0"
androidx-lifecycle-runtime-compose = "androidx.lifecycle:lifecycle-runtime-compose:{lifecycle}"

firebase-bom = "com.google.firebase:firebase-bom:{firebaseBom}"
firebase-auth = { module = "com.google.firebase:firebase-auth-ktx" }
firebase-firestore = { module = "com.google.firebase:firebase-firestore-ktx" }

hilt-android = "com.google.dagger:hilt-android:{hilt}"
hilt-compiler = "com.google.dagger:hilt-compiler:{hilt}"

kotlinx-coroutines-android = "org.jetbrains.kotlinx:kotlinx-coroutines-android:{coroutines}"
kotlinx-coroutines-play-services = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services:{coroutines}"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
google-services = { id = "com.google.gms.google-services", version = "4.4.2" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
